README.md

The "Code of Conduct" link 404s because of the `[USERNAME]` placeholder in the URL.  This PR corrects the URL so it points to the Code of Conduct included in the repo.

Fix Code of Conduct URL in README

---

lib/stytch/oauth.rb
lib/stytch/version.rb

The API now supports using Stytch and IdP sessions at the same time for [the OAuthAuthenticate endpoint](https://stytch.com/docs/api/oauth-authenticate). Users no longer need to specify a `session_management_type` as IdP sessions are always returned now and a Stytch session will be returned if a `session_duration_minutes` is specified.
This is considered a breaking change because we are removing the `session_management_type` field from the input and changing the response to follow the pattern of other authenticate methods.

Add Stytch and IdP sessions at the same time

---

lib/stytch/users.rb
lib/stytch/version.rb

This adds support for the `/users/search` endpoint, including a helper
method that uses the search cursor to build an Enumerator for the full
query results.
Here's an example of usage:
```ruby
query = {
operator: 'AND',
operands: [
{ filter_name: 'email_address_fuzzy', filter_value: 'hopper' },
{ filter_name: 'status', filter_value: 'active' }
]
}
client.users.search_all(query, limit: 10).find_all do |user|
puts user['name']
end
```

feat: Add user search methods

---

lib/stytch/sessions.rb
lib/stytch/version.rb

In session JWTs, the session claim is the more reliable source of the session ID. The "jti" claim
happens to also contain that now, but it will not in the future.

fix: Extract the session ID from the session claim

---

lib/stytch/magic_links.rb
lib/stytch/oauth.rb
lib/stytch/version.rb

Adds `code_challenge` to magic link start methods, and `code_verifier` to magic link and OAuth authenticate methods.
@stytchauth/client-libraries - any suggestion as to whether this should be a patch or a minor?

feat: Add props for PKCE in OAuth and EML flows

---

lib/stytch/client.rb
lib/stytch/version.rb
spec/stytch/client_spec.rb

API client setup uses the `env` value to set the correct base URI for that environment. This is
great for the production live and test environments (which are the only supported ones!), but that
makes it difficult to use this within a Stytch development environment as a Stytch API developer.
So this relaxes the error on the `env` value. If it's one of the two recognized environments,
derive the URL from it. If it's not, but it looks like a URL, treat it as a base URL to use when
building requests.

feat: Allow custom env values for internal dev URLs

---

lib/stytch/crypto_wallets.rb
lib/stytch/magic_links.rb
lib/stytch/otps.rb
lib/stytch/version.rb

This causes a syntax error on `require`, preventing anyone from using the library.
Closes #64

fix: Remove trailing commas in method definitions

---

.github/workflows/ruby.yml
lib/stytch/version.rb
spec/stytch/client_spec.rb
spec/stytch/sessions_spec.rb
stytch.gemspec

This adds a GitHub workflow to run RSpec on PRs for all supported Ruby versions.
RSpec wasn't running the sessions tests because those were written with `test-unit` instead. So I converted them to RSpec tests and removed the `test-unit` dependency.
Unusually for this repo, I intend to rebase-merge instead of squash-merge. So please review the individual commits!

ci: Add test matrix for all supported Ruby versions

---

lib/stytch/magic_links.rb
lib/stytch/otps.rb
lib/stytch/passwords.rb
lib/stytch/version.rb

Adds support for the optional `locale` parameter for the following endpoints:
- /magic_links/email/send
- /magic_links/email/login_or_create
- /magic_links/email/invite
- /otps/email/send
- /otps/email/login_or_create
- /otps/sms/send
- /otps/sms/login_or_create
- /otps/whatsapp/send
- /otps/whatsapp/login_or_create
- /passwords/email/reset/start
The locale parameter specifies the text language of the email that the user receives. Current `locale` options are "en" (English) and "es" (Spanish).
Support for the `locale` parameter has already been added to Stytch's API endpoints: https://github.com/stytchauth/api/pull/1928

[SUP-10] Add locale parameter to Email Magic Links, OTP, and Passwords endpoints

---

lib/stytch/oauth.rb
lib/stytch/version.rb

This adds support for an upcoming endpoint: OAuth Attach (`/v1/oauth/attach`).

feat: Add support for OAuth Attach endpoint

---

lib/stytch/sessions.rb
lib/stytch/version.rb

Adds support for decoding custom claims in local session authentication of JWTs.
Got a sample JWT and showed that this method will extract custom claims:

Decode custom claims in local session auth

---

.gitignore
lib/stytch/b2b_client.rb
lib/stytch/version.rb
spec/stytch/b2b_client_spec.rb
spec/stytch/client_spec.rb
spec/stytch/shared_examples_for_clients.rb

fixes #81 
1. add spec for `StytchB2B::Client` with shared examples based on `Stytch::Client`
2. move `@connection.basic_auth` to `@connection.set_basic_auth`

Fix StytchB2B::Client (fixes #81)

---

lib/stytch/version.rb

I had run a clean on #79 and didn't realize the version change was overridden

Bump major version for Ruby revamp

---

lib/stytch/errors.rb
lib/stytch/m2m.rb
lib/stytch/version.rb

Defines two new errors (JWTExpiredError and TokenMissingScopeError) that extend StandardError
Raises in `authenticate_token` instead of returning `nil` to protect against cases where someone may use authentication in a guard without actually checking the return value

Raise error if token auth fails

---

lib/stytch/b2b_client.rb
lib/stytch/b2b_sessions.rb
lib/stytch/magic_links.rb
lib/stytch/otps.rb
lib/stytch/users.rb
lib/stytch/version.rb

Testing:
* Create b2b magic links invite and send to myself
* Authenticate the magic link and set session_duration_minutes = 120
* Call `b2b_client.sessions.authenticate_jwt_local(authResp["session_jwt"])`
Local auth succeeded

Support local JWT auth in B2B sessions

---

.github/workflows/ruby.yml
.rubocop.yml
DEVELOPMENT.md
stytch.gemspec

This adds a required Rubocop step to the Ruby workflow.
Rubocop accepts a configuration option for the [target Ruby version], which, in our case, defaults to the lowest version number in `stytch.gemspec`.
For now, I think we should run Rubocop just once on that minimum/target Ruby version. But if we have a reason to run it as part of the test matrix, I think that would be fine too.
1. Pull this PR to your local repo
2. `bundle` (see that `rubocop` and `rubocop-rspec` got installed)
3. `bundle exec rubocop` (should report no errors)
I also put up a PR with an intentional linter error in #95 as an example.
[target Ruby version]: https://docs.rubocop.org/rubocop/configuration.html#setting-the-target-ruby-version

dev: Add Rubocop for linting

---

.rubocop.yml

In #94, I chose to disable some Rubocop groups because they weren't related to code correctness. But this library does already conform to most of Rubocop's default Layout and Style rules, so we can re-enable them to keep that consistent.

dev: Enable some Rubocop Layout and Style rules

---

lib/stytch/b2b_sessions.rb
lib/stytch/sessions.rb
lib/stytch/version.rb
spec/stytch/sessions_spec.rb

Fixes #109 
The call to `authenticate_jwt_local` was passing `session_jwt` as a keyword argument instead of positional, which was incorrect calling conventions for the method.
Created a session using PW auth -> called authenticate_jwt -> verified it auth'd the JWT without making a network request

Fix local JWT auth

---

lib/stytch/b2b_discovery.rb
lib/stytch/b2b_organizations.rb
lib/stytch/b2b_rbac.rb
lib/stytch/passwords.rb
lib/stytch/version.rb

1. Docs updates
2. Adds support for `set_email_verified` in passwords/migrate

Update docs and support set_email_verified

---

lib/stytch.rb
lib/stytch/b2b_magic_links.rb
lib/stytch/b2b_organizations.rb
lib/stytch/b2b_scim.rb
lib/stytch/b2b_sso.rb
lib/stytch/version.rb

This is a MAJOR upgrade -- we weren't previously rendering RBAC method options correctly, which meant most never showed up. Those that _did_ show up were not actually showing up in a helpful location, so they are now being nested under the appropriate class that needs those options.

Fix Ruby RBAC options not being rendered

---

.rubocop.yml
lib/stytch/errors.rb
lib/stytch/m2m.rb
lib/stytch/version.rb
spec/stytch/m2m_spec.rb
spec/stytch/sessions_spec.rb
stytch.gemspec

This PR adds support for wildcard scopes in M2M auth.
This means that an M2M client can have a scope like `read:*` and if given a required scope of `read:foo`, authentication will be allowed.
This does *not* affect "simple" scopes like `read` or `read_users` -- only scopes with a separating `:` are supported.
Furthermore, the assumption is that the scopes will be given as `action:resource`, though it is technically possible to assign in a different way like `users:read`, though in that case, a scope of `users:*` would **not** match a required scope of `read:users`. But as long as an application is consistent, this would be allowed.
Furthermore, a scope of just `*` does **not** get interpreted as an "omniscient" client -- instead, this is seen as the literal character `*` and gets matched …

Support wildcard scopes in M2M auth

---

README.md

Adds in examples for B2B paths to readme to align with the java SDK's.

Add in b2b examples

---

DEVELOPMENT.md
README.md

Update Slack Invite links to point to the Support landing page as a single source of truth (Slack invite links expire after 400 uses and need to be updated semi frequently).

Update slack links

---

.rubocop.yml
lib/stytch/b2b_client.rb
lib/stytch/b2b_magic_links.rb
lib/stytch/b2b_organizations.rb
lib/stytch/b2b_passwords.rb
lib/stytch/b2b_scim.rb
lib/stytch/b2b_sessions.rb
lib/stytch/b2b_sso.rb
lib/stytch/client.rb
lib/stytch/m2m.rb
lib/stytch/passwords.rb
lib/stytch/sessions.rb
lib/stytch/version.rb
spec/stytch/m2m_spec.rb
spec/stytch/sessions_spec.rb

This PR adds the following changes:
- Fixes M2M token authentication by adding `headers` to `get_request` and specifying whether to use the B2B or B2C JWKS endpoint
- Adds `clock_tolerance_seconds` as an optional parameter to `authenticate_jwt`, `authenticate_jwt_local` in the B2B and B2C sessions clients, and to `authenticate_token` and `authenticate_token_local` for M2M. This is used as the `nbf_leeway` value to JWT verification to help with clock drift issues.
- Fixes various RBAC docs that had some unintended trailing markdoc characters
- Codegen: SCIM groups, RBAC headers for revoke session, and various docs updates

Fix M2M authentication and add clock tolerance to JWT methods

---

lib/stytch/m2m.rb
lib/stytch/version.rb

* When the `post_request` is called, it already  returns parsed JSON. Believed to have been  introduced in `3663ee5cc5d72bbd24e7d3daa34c623f421339ac`
* Bump patch version

Fix double JSON.parse of M2M::token

---

lib/stytch/fraud.rb
lib/stytch/version.rb

This PR adds support for IPGEO in the fraud rules endpoint. You can now set rules on CIDR blocks, ASNs, and country codes. The fingerprint lookup endpoint will now also return information on which rule type and identifier were applied, if a `RULE_MATCH` reason was returned.

Add IPGEO to DFP rules endpoint

---

lib/stytch/b2b_sessions.rb
lib/stytch/m2m.rb
lib/stytch/sessions.rb
lib/stytch/version.rb
spec/stytch/sessions_spec.rb

When using custom base URLs to call our API we return a different issuer. This is to be compliant with OIDC JWTs. We should accept these for our local validation!

Accept BaseURL as Issuer
